import { controlCenterStore, type ControlCenterSeedData } from "./store.js";
import type {
  AgentSpec,
  AgentSpecVersion,
  UseCase,
  UseCaseVersion,
  AgentCapability,
  Tool,
  AgentTool,
  Integration,
  DevTask,
  ImplComponent,
} from "@milo/shared";

const now = new Date().toISOString();

// ─── CAPABILITIES ─────────────────────────────────────────────

const allCapabilities: AgentCapability[] = [
  {
    id: "cap-pdf-parsing", capabilityCode: "pdf_parsing", name: "PDF Parsing",
    description: "Extrakce textu, metadat a struktury z PDF dokumentů",
    inputs: [{ name: "file", type: "binary/pdf" }],
    outputs: [{ name: "text", type: "string" }, { name: "metadata", type: "object" }],
    apiInterface: null, dependencies: [], status: "planned", maturityLevel: "concept",
    owner: "engineering", activeVersion: null, progressPercent: 0, createdAt: now, updatedAt: now,
  },
  {
    id: "cap-ocr", capabilityCode: "ocr", name: "OCR",
    description: "Optické rozpoznávání znaků z obrázků a naskenovaných dokumentů",
    inputs: [{ name: "image", type: "binary/image" }],
    outputs: [{ name: "text", type: "string" }],
    apiInterface: null, dependencies: [], status: "planned", maturityLevel: "concept",
    owner: "engineering", activeVersion: null, progressPercent: 0, createdAt: now, updatedAt: now,
  },
  {
    id: "cap-metadata-extraction", capabilityCode: "metadata_extraction", name: "Metadata Extraction",
    description: "Extrakce strukturovaných metadat z dokumentů (lhůty, osoby, organizace, částky)",
    inputs: [{ name: "text", type: "string" }],
    outputs: [{ name: "entities", type: "object" }],
    apiInterface: null, dependencies: ["cap-pdf-parsing", "cap-ocr"], status: "planned", maturityLevel: "concept",
    owner: "engineering", activeVersion: null, progressPercent: 0, createdAt: now, updatedAt: now,
  },
  {
    id: "cap-deadline-extraction", capabilityCode: "deadline_extraction", name: "Deadline Extraction",
    description: "Vytěžení lhůt a termínů z dokumentů",
    inputs: [{ name: "text", type: "string" }],
    outputs: [{ name: "deadlines", type: "array" }],
    apiInterface: null, dependencies: ["cap-metadata-extraction"], status: "planned", maturityLevel: "concept",
    owner: "engineering", activeVersion: null, progressPercent: 0, createdAt: now, updatedAt: now,
  },
  {
    id: "cap-legal-entity-extraction", capabilityCode: "legal_entity_extraction", name: "Legal Entity Extraction",
    description: "Vytěžení osob, organizací, částek a právních ustanovení",
    inputs: [{ name: "text", type: "string" }],
    outputs: [{ name: "persons", type: "array" }, { name: "organizations", type: "array" }, { name: "amounts", type: "array" }, { name: "legal_provisions", type: "array" }],
    apiInterface: null, dependencies: ["cap-metadata-extraction"], status: "planned", maturityLevel: "concept",
    owner: "engineering", activeVersion: null, progressPercent: 0, createdAt: now, updatedAt: now,
  },
  {
    id: "cap-timeline-generation", capabilityCode: "timeline_generation", name: "Timeline Generation",
    description: "Vytvoření časové osy z událostí a lhůt",
    inputs: [{ name: "events", type: "array" }],
    outputs: [{ name: "timeline", type: "object" }],
    apiInterface: null, dependencies: ["cap-deadline-extraction"], status: "planned", maturityLevel: "concept",
    owner: "engineering", activeVersion: null, progressPercent: 0, createdAt: now, updatedAt: now,
  },
  {
    id: "cap-evidence-linking", capabilityCode: "evidence_linking", name: "Evidence Linking",
    description: "Propojování důkazních dokumentů s entitami a tvrzeními",
    inputs: [{ name: "documents", type: "array" }, { name: "entities", type: "array" }],
    outputs: [{ name: "links", type: "array" }],
    apiInterface: null, dependencies: [], status: "planned", maturityLevel: "concept",
    owner: "engineering", activeVersion: null, progressPercent: 0, createdAt: now, updatedAt: now,
  },
  {
    id: "cap-draft-generation", capabilityCode: "draft_generation", name: "Draft Generation",
    description: "Generování konceptů dokumentů a podání",
    inputs: [{ name: "template", type: "string" }, { name: "data", type: "object" }],
    outputs: [{ name: "draft", type: "string" }],
    apiInterface: null, dependencies: [], status: "planned", maturityLevel: "concept",
    owner: "engineering", activeVersion: null, progressPercent: 0, createdAt: now, updatedAt: now,
  },
  {
    id: "cap-email-triage", capabilityCode: "email_triage", name: "Email Triage",
    description: "Třídění Gmailu, vytváření štítků a nastavování filtrů",
    inputs: [{ name: "messages", type: "array" }],
    outputs: [{ name: "categorized", type: "object" }],
    apiInterface: null, dependencies: [], status: "planned", maturityLevel: "concept",
    owner: "engineering", activeVersion: null, progressPercent: 0, createdAt: now, updatedAt: now,
  },
  {
    id: "cap-ai-summary", capabilityCode: "ai_summary", name: "AI Summary",
    description: "AI shrnutí zpráv, dokumentů a konverzací",
    inputs: [{ name: "text", type: "string" }],
    outputs: [{ name: "summary", type: "string" }],
    apiInterface: null, dependencies: [], status: "planned", maturityLevel: "concept",
    owner: "engineering", activeVersion: null, progressPercent: 0, createdAt: now, updatedAt: now,
  },
  {
    id: "cap-code-search", capabilityCode: "code_search", name: "Code Search",
    description: "Vyhledávání v kódu, diagnostika chyb",
    inputs: [{ name: "query", type: "string" }],
    outputs: [{ name: "results", type: "array" }],
    apiInterface: null, dependencies: [], status: "planned", maturityLevel: "concept",
    owner: "engineering", activeVersion: null, progressPercent: 0, createdAt: now, updatedAt: now,
  },
  {
    id: "cap-git-operations", capabilityCode: "git_operations", name: "Git Operations",
    description: "Práce s gitem — branch, commit, push, pull request",
    inputs: [{ name: "operation", type: "string" }],
    outputs: [{ name: "result", type: "object" }],
    apiInterface: null, dependencies: [], status: "planned", maturityLevel: "concept",
    owner: "engineering", activeVersion: null, progressPercent: 0, createdAt: now, updatedAt: now,
  },
];

// ─── TOOLS ────────────────────────────────────────────────────

const allTools: Tool[] = [
  { id: "tool-filesystem", name: "filesystem", type: "local", provider: null, description: "Lokální souborový systém", configurationSchema: null, secretReference: null, availabilityStatus: "available", healthStatus: "healthy", riskLevel: "low", createdAt: now },
  { id: "tool-github", name: "github", type: "external", provider: "GitHub API", description: "GitHub operace", configurationSchema: null, secretReference: "GITHUB_TOKEN", availabilityStatus: "unconfigured", healthStatus: "unknown", riskLevel: "medium", createdAt: now },
  { id: "tool-shell", name: "shell", type: "local", provider: null, description: "Shell příkazy", configurationSchema: null, secretReference: null, availabilityStatus: "available", healthStatus: "healthy", riskLevel: "high", createdAt: now },
  { id: "tool-code-search", name: "code-search", type: "local", provider: null, description: "Vyhledávání v kódu", configurationSchema: null, secretReference: null, availabilityStatus: "available", healthStatus: "healthy", riskLevel: "low", createdAt: now },
  { id: "tool-gmail", name: "gmail", type: "external", provider: "Google Gmail API", description: "Gmail integrace", configurationSchema: null, secretReference: "GOOGLE_CREDENTIALS", availabilityStatus: "configured", healthStatus: "healthy", riskLevel: "medium", createdAt: now },
  { id: "tool-calendar", name: "calendar", type: "external", provider: "Google Calendar API", description: "Google Kalendář", configurationSchema: null, secretReference: "GOOGLE_CREDENTIALS", availabilityStatus: "configured", healthStatus: "healthy", riskLevel: "low", createdAt: now },
  { id: "tool-obsidian", name: "obsidian", type: "local", provider: null, description: "Obsidian vault", configurationSchema: null, secretReference: null, availabilityStatus: "available", healthStatus: "healthy", riskLevel: "low", createdAt: now },
  { id: "tool-drive", name: "drive", type: "external", provider: "Google Drive API", description: "Google Drive", configurationSchema: null, secretReference: "GOOGLE_CREDENTIALS", availabilityStatus: "configured", healthStatus: "healthy", riskLevel: "low", createdAt: now },
  { id: "tool-web-search", name: "web-search", type: "external", provider: null, description: "Web vyhledávání", configurationSchema: null, secretReference: null, availabilityStatus: "available", healthStatus: "healthy", riskLevel: "low", createdAt: now },
  { id: "tool-pdf-parser", name: "pdf-parser", type: "local", provider: null, description: "PDF Parser", configurationSchema: null, secretReference: null, availabilityStatus: "available", healthStatus: "healthy", riskLevel: "low", createdAt: now },
  { id: "tool-isds", name: "isds", type: "external", provider: "ISDS API", description: "Datové schránky", configurationSchema: null, secretReference: "ISDS_CREDENTIALS", availabilityStatus: "unconfigured", healthStatus: "unknown", riskLevel: "high", createdAt: now },
  { id: "tool-weather", name: "weather", type: "external", provider: "OpenWeather", description: "Počasí", configurationSchema: null, secretReference: null, availabilityStatus: "available", healthStatus: "healthy", riskLevel: "low", createdAt: now },
  { id: "tool-markdown", name: "markdown", type: "local", provider: null, description: "Markdown processing", configurationSchema: null, secretReference: null, availabilityStatus: "available", healthStatus: "healthy", riskLevel: "low", createdAt: now },
  { id: "tool-embeddings", name: "embeddings", type: "internal", provider: "OpenAI", description: "Generování embeddings", configurationSchema: null, secretReference: "OPENAI_API_KEY", availabilityStatus: "available", healthStatus: "healthy", riskLevel: "low", createdAt: now },
  { id: "tool-vector-store", name: "vector-store", type: "internal", provider: "pgvector", description: "Vector store", configurationSchema: null, secretReference: null, availabilityStatus: "planned", healthStatus: "unknown", riskLevel: "low", createdAt: now },
  { id: "tool-n8n", name: "n8n", type: "external", provider: "n8n", description: "Workflow automatizace", configurationSchema: null, secretReference: null, availabilityStatus: "planned", healthStatus: "unknown", riskLevel: "low", createdAt: now },
  { id: "tool-home-assistant", name: "home-assistant", type: "external", provider: "Home Assistant", description: "Smart home", configurationSchema: null, secretReference: null, availabilityStatus: "planned", healthStatus: "unknown", riskLevel: "low", createdAt: now },
  { id: "tool-github-actions", name: "github-actions", type: "external", provider: "GitHub Actions", description: "CI/CD pipeliny", configurationSchema: null, secretReference: "GITHUB_TOKEN", availabilityStatus: "unconfigured", healthStatus: "unknown", riskLevel: "medium", createdAt: now },
];

// ─── INTEGRATIONS ─────────────────────────────────────────────

const allIntegrations: Integration[] = [
  { id: "int-gmail", slug: "gmail", name: "Gmail", type: "external", provider: "Google", description: "Email integrace", configSchema: null, status: "configured", healthStatus: "healthy", createdAt: now },
  { id: "int-calendar", slug: "google-calendar", name: "Google Calendar", type: "external", provider: "Google", description: "Kalendářová integrace", configSchema: null, status: "configured", healthStatus: "healthy", createdAt: now },
  { id: "int-drive", slug: "google-drive", name: "Google Drive", type: "external", provider: "Google", description: "Cloudové úložiště", configSchema: null, status: "configured", healthStatus: "healthy", createdAt: now },
  { id: "int-github", slug: "github", name: "GitHub", type: "external", provider: "GitHub", description: "Repozitáře a CI/CD", configSchema: null, status: "planned", healthStatus: "unknown", createdAt: now },
  { id: "int-supabase", slug: "supabase", name: "Supabase", type: "infrastructure", provider: "Supabase", description: "Databáze a auth", configSchema: null, status: "configured", healthStatus: "healthy", createdAt: now },
  { id: "int-n8n", slug: "n8n", name: "n8n", type: "external", provider: "n8n", description: "Workflow automatizace", configSchema: null, status: "planned", healthStatus: "unknown", createdAt: now },
  { id: "int-telegram", slug: "telegram", name: "Telegram", type: "external", provider: "Telegram", description: "Messaging", configSchema: null, status: "planned", healthStatus: "unknown", createdAt: now },
  { id: "int-obsidian", slug: "obsidian", name: "Obsidian", type: "local", provider: null, description: "Knowledge base", configSchema: null, status: "available", healthStatus: "healthy", createdAt: now },
  { id: "int-ollama", slug: "ollama", name: "Ollama", type: "local", provider: null, description: "Lokální LLM", configSchema: null, status: "planned", healthStatus: "unknown", createdAt: now },
  { id: "int-openrouter", slug: "openrouter", name: "OpenRouter", type: "external", provider: "OpenRouter", description: "Multi-model API", configSchema: null, status: "planned", healthStatus: "unknown", createdAt: now },
  { id: "int-deepseek", slug: "deepseek", name: "DeepSeek", type: "external", provider: "DeepSeek", description: "DeepSeek API", configSchema: null, status: "planned", healthStatus: "unknown", createdAt: now },
  { id: "int-docker", slug: "docker", name: "Docker", type: "infrastructure", provider: null, description: "Kontejnerizace", configSchema: null, status: "available", healthStatus: "healthy", createdAt: now },
];

// ─── AGENTS ───────────────────────────────────────────────────

const allAgents: AgentSpec[] = [
  {
    id: "chief-of-staff", slug: "chief-of-staff", name: "Chief of Staff",
    description: "Digitální ředitel kanceláře — plánuje, prioritizuje, deleguje, kontroluje, reportuje a komunikuje s uživatelem",
    purpose: "Koordinovat všechny agenty, připravovat denní briefing, prioritizovat a delegovat úkoly",
    category: "coordinator", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "critical", riskLevel: "low",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "partial", runtimeStatus: "simulated", progressPercent: 45,
    tags: ["a_Team"],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "developer", slug: "developer-agent", name: "Developer Agent",
    description: "Senior software engineer pro vývoj, code review a architekturu",
    purpose: "Implementovat funkce, opravovat chyby, provádět code review a pomáhat s technickými rozhodnutími",
    category: "engineering", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "high", riskLevel: "medium",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "partial", runtimeStatus: "simulated", progressPercent: 35,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "research", slug: "research-agent", name: "Research Agent",
    description: "Research analytik pro information retrieval, analýzu a sumarizaci",
    purpose: "Vyhledávat informace, analyzovat dokumenty a připravovat rešerše",
    category: "knowledge", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "normal", riskLevel: "low",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "partial", runtimeStatus: "simulated", progressPercent: 40,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "knowledge", slug: "knowledge-agent", name: "Knowledge Agent",
    description: "Správce znalostní báze — indexing, vector search, knowledge graphs",
    purpose: "Indexovat dokumenty a zajišťovat vyhledávání napříč zdroji",
    category: "knowledge", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "high", riskLevel: "low",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "not_started", runtimeStatus: "offline", progressPercent: 5,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "legal", slug: "legal-agent", name: "Legal Agent",
    description: "Právní analytik pro contract analysis, legal research a compliance",
    purpose: "Analyzovat právní dokumenty, smlouvy a rizika, vytěžovat entity a lhůty",
    category: "legal", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "high", riskLevel: "high",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "not_started", runtimeStatus: "offline", progressPercent: 5,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "document", slug: "document-agent", name: "Document Agent",
    description: "Zpracovatel dokumentů — parsování, extrakce, generování",
    purpose: "Extrahovat data z dokumentů a generovat přehledné výstupy",
    category: "knowledge", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "normal", riskLevel: "low",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "not_started", runtimeStatus: "offline", progressPercent: 5,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "calendar", slug: "calendar-agent", name: "Calendar Agent",
    description: "Osobní manažer času — scheduling, meeting prep, focus time, deep work",
    purpose: "Aktivně řídit čas uživatele — synchronizovat kalendáře, detekovat kolize, optimalizovat den",
    category: "productivity", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "normal", riskLevel: "low",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "partial", runtimeStatus: "simulated", progressPercent: 50,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "secretary", slug: "communication-agent", name: "Communication Agent",
    description: "Osobní komunikační manažer — email triage, AI shrnutí, návrhy odpovědí",
    purpose: "Řídit příchozí i odchozí komunikaci, minimalizovat čas strávený emaily",
    category: "communication", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "normal", riskLevel: "medium",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "partial", runtimeStatus: "simulated", progressPercent: 45,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "automation", slug: "automation-agent", name: "Automation Agent",
    description: "Automatizační inženýr — workflow automation, scripting, integrations",
    purpose: "Navrhovat a spouštět opakující se workflow",
    category: "engineering", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "low", riskLevel: "low",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "not_started", runtimeStatus: "offline", progressPercent: 5,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "legal-case-agent", slug: "legal-case-agent", name: "Právní a důkazní agent",
    description: "Analyzuje právní dokumenty, vytěžuje entity, lhůty, vytváří časové osy a důkazní balíčky",
    purpose: "Komplexní zpracování právních kauz — od dokumentu přes analýzu po podání",
    category: "legal", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "high", riskLevel: "high",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "not_started", runtimeStatus: "offline", progressPercent: 3,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "email-comm-agent", slug: "email-comm-agent", name: "E-mailový a komunikační agent",
    description: "Třídění Gmailu, vyhodnocení priority, návrhy odpovědí, follow-up",
    purpose: "Kompletní správa emailové komunikace",
    category: "communication", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "normal", riskLevel: "medium",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "not_started", runtimeStatus: "offline", progressPercent: 5,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "tjk-agent", slug: "tjk-agent", name: "TJK Agent",
    description: "Správa TJ Krupka — členové, příspěvky, výbor, oddíly, tréninky, soutěže",
    purpose: "Kompletní správa tělovýchovné jednoty",
    category: "organization", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "high", riskLevel: "medium",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "not_started", runtimeStatus: "offline", progressPercent: 3,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "komarka-agent", slug: "komarka-agent", name: "Komárka Agent",
    description: "Projektová dokumentace, majetková mapa, harmonogram, dotace",
    purpose: "Správa projektu Komárka — od dokumentace po dotační příležitosti",
    category: "project", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "high", riskLevel: "medium",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "not_started", runtimeStatus: "offline", progressPercent: 3,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "tmobile-agent", slug: "tmobile-agent", name: "T-Mobile a infrastruktura Agent",
    description: "Smluvní kontrola, platební kontrola, kalkulace nákladů, incident management",
    purpose: "Správa telekomunikační infrastruktury",
    category: "infrastructure", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "high", riskLevel: "medium",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "not_started", runtimeStatus: "offline", progressPercent: 3,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "krupka-agent", slug: "krupka-agent", name: "Město Krupka Agent",
    description: "Monitoring rady a zastupitelstva, kontrola usnesení, žádosti podle 106/1999 Sb.",
    purpose: "Monitoring a analýza městské samosprávy",
    category: "legal", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "normal", riskLevel: "low",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "not_started", runtimeStatus: "offline", progressPercent: 3,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "finance-agent", slug: "finance-agent", name: "Finanční Agent",
    description: "Bankovní výpisy, faktury, párování plateb, cash flow, kontrola výdajů",
    purpose: "Kompletní správa osobních a projektových financí",
    category: "finance", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "high", riskLevel: "high",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "not_started", runtimeStatus: "offline", progressPercent: 3,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "infra-agent", slug: "infrastructure-agent", name: "Infrastrukturní Agent",
    description: "Monitoring VPS, Docker, databáze, zálohování, bezpečnost",
    purpose: "Správa serverové infrastruktury",
    category: "infrastructure", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "high", riskLevel: "high",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "not_started", runtimeStatus: "offline", progressPercent: 5,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "webdo24-agent", slug: "webdo24-agent", name: "Webdo24 Agent",
    description: "Správa zákazníků, monitoring webů, expirace domén, fakturace",
    purpose: "Správa webhostingové firmy Webdo24",
    category: "business", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "normal", riskLevel: "medium",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "not_started", runtimeStatus: "offline", progressPercent: 3,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "personal-assistant", slug: "personal-assistant", name: "Osobní Asistent",
    description: "Hlasové úkoly, kalendář, připomenutí, příprava na schůzky",
    purpose: "Osobní asistence pro každodenní život",
    category: "productivity", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "normal", riskLevel: "low",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "not_started", runtimeStatus: "offline", progressPercent: 5,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "research-agent-intel", slug: "research-intel-agent", name: "Výzkumný a zpravodajský Agent",
    description: "Právní, dotační a technologický monitoring, konkurenční výzkum",
    purpose: "Monitoring příležitostí a hrozeb",
    category: "knowledge", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "normal", riskLevel: "low",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "not_started", runtimeStatus: "offline", progressPercent: 3,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "notifier", slug: "notifier-agent", name: "Notifier Agent",
    description: "Synchronizace připomínek, doručování notifikací, detekce checkpointů",
    purpose: "Zajistit, aby uživatel nezmeškal žádný termín",
    category: "productivity", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "high", riskLevel: "low",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "partial", runtimeStatus: "simulated", progressPercent: 40,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "tester-boss", slug: "tester-boss", name: "Tester BOSS",
    description: "Testuje, kontroluje a vyhodnocuje agenty a jejich výstupy. Nikdy nic neopravuje.",
    purpose: "Provádět testy, vytvářet zprávy, připravovat návrhy na opravy a vylepšení",
    category: "quality", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "high", riskLevel: "low",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "not_started", runtimeStatus: "offline", progressPercent: 5,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "spy-g", slug: "spy-g", name: "SPY_G",
    description: "Skrytý pozorovatel — naslouchá, zaznamenává, hodnotí důležitost a relevanci. Dohlíží na gamechanger nápady.",
    purpose: "Zachytit důležité nápady a požadavky, které by se mohly ztratit, a dohlížet na jejich realizaci",
    category: "observer", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "high", riskLevel: "low",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "not_started", runtimeStatus: "offline", progressPercent: 5,
    tags: [],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
  {
    id: "phone-tracker", slug: "phone-tracker", name: "Phone Tracker",
    description: "Eviduje real-time data telefonu — GPS souřadnice, soubory a timestampy. Pasivní agent, výstupy jen na vyžádání.",
    purpose: "Ukládat a na vyžádání dotazovat GPS data, soubory a timestampy z telefonu",
    category: "data", owner: "owner", status: "specified",
    lifecycleStatus: "specified", priority: "high", riskLevel: "low",
    activeVersionId: null, deployedVersionId: null,
    implementationStatus: "not_started", runtimeStatus: "offline", progressPercent: 5,
    tags: ["a_Team"],
    createdAt: now, updatedAt: now, archivedAt: null,
  },
];

// ─── AGENT VERSIONS ───────────────────────────────────────────

const allAgentVersions: Omit<AgentSpecVersion, "id" | "createdAt">[] = allAgents.map((a) => ({
  agentId: a.id,
  versionNumber: 1,
  versionLabel: "v1.0-initial",
  specification: {
    name: a.name,
    purpose: a.purpose,
    description: a.description,
    category: a.category,
    priority: a.priority,
    riskLevel: a.riskLevel,
  },
  changeSummary: "Počáteční definice agenta",
  changeReason: "Inicializace specifikace",
  createdBy: "system",
  parentVersionId: null,
  status: "draft",
  approvedAt: null,
  deployedAt: null,
}));

// ─── USE CASES ────────────────────────────────────────────────

const useCases: UseCase[] = [
  // Chief of Staff
  { id: "uc-cos-briefing", agentId: "chief-of-staff", slug: "daily-briefing", name: "Denní briefing", description: "Každé ráno připravit briefing o stavu systému, prioritách a úkolech", purpose: "Poskytnout vlastníkovi přehled dne", triggerDescription: "Spuštění každé ráno v 7:00", category: "core", priority: "critical", riskLevel: "low", status: "ready_for_planning", implementationStatus: "partial", progressPercent: 30, activeVersionId: null, createdAt: now, updatedAt: now },
  { id: "uc-cos-prioritize", agentId: "chief-of-staff", slug: "prioritization", name: "Prioritizace úkolů", description: "Automatická prioritizace příchozích úkolů podle důležitosti a termínů", purpose: "Udržovat pořádek v backlogu", triggerDescription: "Nový úkol nebo změna priority", category: "core", priority: "critical", riskLevel: "low", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: now },
  { id: "uc-cos-delegate", agentId: "chief-of-staff", slug: "delegation", name: "Delegace práce", description: "Rozdělení práce mezi agenty podle jejich schopností a vytížení", purpose: "Efektivní využití všech agentů", triggerDescription: "Nový úkol k delegování", category: "core", priority: "high", riskLevel: "low", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: now },
  { id: "uc-cos-check", agentId: "chief-of-staff", slug: "completion-check", name: "Kontrola dokončení", description: "Kontrola dokončených úkolů a jejich kvality", purpose: "Validace výstupů agentů", triggerDescription: "Dokončení úkolu agentem", category: "core", priority: "high", riskLevel: "low", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: now },

  // Developer
  { id: "uc-dev-diagnose", agentId: "developer", slug: "bug-diagnosis", name: "Diagnostika chyby", description: "Analýza nahlášené chyby, reprodukce, identifikace příčiny", purpose: "Rychle najít a opravit chyby", triggerDescription: "Hlášení chyby nebo selhání testu", category: "core", priority: "critical", riskLevel: "medium", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: now },
  { id: "uc-dev-implement", agentId: "developer", slug: "feature-implementation", name: "Implementace funkce", description: "Implementace nové funkce podle specifikace", purpose: "Dodávat nové schopnosti do systému", triggerDescription: "Vývojový úkol", category: "core", priority: "high", riskLevel: "medium", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: now },
  { id: "uc-dev-test", agentId: "developer", slug: "testing", name: "Testování", description: "Vytváření a spouštění testů, kontrola coverage", purpose: "Udržovat kvalitu kódu", triggerDescription: "Po implementaci", category: "core", priority: "high", riskLevel: "low", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: now },

  // Research
  { id: "uc-research-search", agentId: "research", slug: "information-retrieval", name: "Vyhledávání informací", description: "Vyhledávání relevantních informací napříč zdroji", purpose: "Poskytovat podložené odpovědi", triggerDescription: "Výzkumný dotaz", category: "core", priority: "high", riskLevel: "low", status: "ready_for_planning", implementationStatus: "partial", progressPercent: 20, activeVersionId: null, createdAt: now, updatedAt: now },
  { id: "uc-research-analyze", agentId: "research", slug: "document-analysis", name: "Analýza dokumentů", description: "Hloubková analýza dokumentů a extrakce klíčových informací", purpose: "Připravit podklady pro rozhodování", triggerDescription: "Nový dokument", category: "core", priority: "high", riskLevel: "medium", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: now },

  // Legal Case Agent
  { id: "uc-legal-process", agentId: "legal-case-agent", slug: "process-legal-document", name: "Zpracování právního dokumentu", description: "OCR, vytěžení lhůt, osob, organizací, částek a právních ustanovení", purpose: "Kompletní extrakce dat z právního dokumentu", triggerDescription: "Nahrání právního dokumentu", category: "core", priority: "critical", riskLevel: "high", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: now },
  { id: "uc-legal-timeline", agentId: "legal-case-agent", slug: "timeline-generation", name: "Vytvoření časové osy", description: "Vytvoření chronologické časové osy kauzy z dokumentů a událostí", purpose: "Přehledná vizualizace průběhu kauzy", triggerDescription: "Zpracování dokumentů", category: "core", priority: "high", riskLevel: "medium", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: now },
  { id: "uc-legal-evidence", agentId: "legal-case-agent", slug: "evidence-package", name: "Důkazní balíček", description: "Sestavení důkazního balíčku s propojením na entity a časovou osu", purpose: "Systematická evidence pro právní jednání", triggerDescription: "Požadavek na důkazní balíček", category: "core", priority: "critical", riskLevel: "high", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: now },
  { id: "uc-legal-submission", agentId: "legal-case-agent", slug: "prepare-submission", name: "Příprava podání", description: "Příprava právního podání, vyžaduje schválení před odesláním", purpose: "Generování podání s bezpečnostní kontrolou", triggerDescription: "Schválený koncept podání", category: "core", priority: "critical", riskLevel: "critical", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: now },

  // Email/Communication
  { id: "uc-email-triage", agentId: "email-comm-agent", slug: "email-triage", name: "Třídění Gmailu", description: "Automatické třídění emailů, vytváření štítků a filtrů", purpose: "Snížit chaos v inboxu", triggerDescription: "Nový email", category: "core", priority: "high", riskLevel: "medium", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: now },
  { id: "uc-email-reply", agentId: "email-comm-agent", slug: "draft-reply", name: "Návrh odpovědi", description: "AI generování návrhu odpovědi s možností úpravy a schválení", purpose: "Ušetřit čas při odpovídání", triggerDescription: "Příchozí email vyžadující odpověď", category: "core", priority: "high", riskLevel: "medium", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: now },

  // TJK
  { id: "uc-tjk-members", agentId: "tjk-agent", slug: "member-management", name: "Správa členů", description: "Evidence členů, platnost registrací, oddíly", purpose: "Přehledná správa členské základny", triggerDescription: "Změna v členské evidenci", category: "core", priority: "high", riskLevel: "medium", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: now },
  { id: "uc-tjk-meeting", agentId: "tjk-agent", slug: "board-preparation", name: "Příprava výboru", description: "Příprava podkladů pro jednání výboru, zápis, usnesení", purpose: "Efektivní jednání výboru", triggerDescription: "Plánované jednání výboru", category: "core", priority: "high", riskLevel: "low", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: now },

  // Finance
  { id: "uc-fin-bank", agentId: "finance-agent", slug: "bank-statements", name: "Bankovní výpisy", description: "Automatické zpracování bankovních výpisů, kategorizace transakcí", purpose: "Automatizace účetnictví", triggerDescription: "Nový bankovní výpis", category: "core", priority: "critical", riskLevel: "high", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: now },
  { id: "uc-fin-match", agentId: "finance-agent", slug: "payment-matching", name: "Párování plateb", description: "Automatické párování příchozích plateb s fakturami", purpose: "Udržovat přehled o pohledávkách", triggerDescription: "Nová platba", category: "core", priority: "high", riskLevel: "medium", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: now },

  // Infra
  { id: "uc-infra-monitor", agentId: "infra-agent", slug: "vps-monitoring", name: "Monitoring VPS", description: "Kontinuální monitoring serverů, CPU, RAM, disk", purpose: "Zachytit problém dříve než uživatel", triggerDescription: "Pravidelná kontrola", category: "core", priority: "critical", riskLevel: "high", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: now },
  { id: "uc-infra-backup", agentId: "infra-agent", slug: "backup", name: "Zálohování", description: "Automatické zálohování databází, souborů, konfigurací", purpose: "Ochrana proti ztrátě dat", triggerDescription: "Plánované zálohování", category: "core", priority: "critical", riskLevel: "high", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: now },

  // Krupka
  { id: "uc-krupka-monitor", agentId: "krupka-agent", slug: "council-monitoring", name: "Monitoring rady a zastupitelstva", description: "Sledování programu, usnesení a hlasování", purpose: "Transparentnost místní samosprávy", triggerDescription: "Zveřejnění programu jednání", category: "core", priority: "high", riskLevel: "low", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: now },
  { id: "uc-krupka-106", agentId: "krupka-agent", slug: "info-request", name: "Žádosti podle 106/1999 Sb.", description: "Příprava a sledování žádostí o informace", purpose: "Efektivní využití zákona o svobodném přístupu k informacím", triggerDescription: "Potřeba získat informace", category: "core", priority: "high", riskLevel: "low", status: "draft", implementationStatus: "not_started", progressPercent: 0, activeVersionId: null, createdAt: now, updatedAt: null },
];

// ─── USE CASE VERSIONS ────────────────────────────────────────

const useCaseVersions: Omit<UseCaseVersion, "id" | "createdAt">[] = useCases.map((uc) => ({
  useCaseId: uc.id,
  versionNumber: 1,
  versionLabel: "v1.0-initial",
  purpose: uc.purpose,
  triggerDescription: uc.triggerDescription,
  inputs: [],
  preconditions: [],
  workflowSteps: [],
  decisionRules: [],
  tools: [],
  integrations: [],
  outputs: [],
  persistenceRules: null,
  approvalRules: {},
  securityRules: {},
  failureStates: [],
  fallbackBehavior: null,
  testScenarios: [],
  definitionOfDone: [],
  observabilityRequirements: {},
  specification: { name: uc.name, description: uc.description, purpose: uc.purpose },
  changeSummary: "Počáteční definice use case",
  createdBy: "system",
  status: "draft",
}));

// ─── AGENT CAPABILITIES ───────────────────────────────────────

const agentCaps: { agentId: string; capabilityId: string }[] = [
  { agentId: "developer", capabilityId: "cap-code-search" },
  { agentId: "developer", capabilityId: "cap-git-operations" },
  { agentId: "research", capabilityId: "cap-ai-summary" },
  { agentId: "legal-case-agent", capabilityId: "cap-pdf-parsing" },
  { agentId: "legal-case-agent", capabilityId: "cap-ocr" },
  { agentId: "legal-case-agent", capabilityId: "cap-metadata-extraction" },
  { agentId: "legal-case-agent", capabilityId: "cap-deadline-extraction" },
  { agentId: "legal-case-agent", capabilityId: "cap-legal-entity-extraction" },
  { agentId: "legal-case-agent", capabilityId: "cap-timeline-generation" },
  { agentId: "legal-case-agent", capabilityId: "cap-evidence-linking" },
  { agentId: "legal-case-agent", capabilityId: "cap-draft-generation" },
  { agentId: "email-comm-agent", capabilityId: "cap-email-triage" },
  { agentId: "email-comm-agent", capabilityId: "cap-ai-summary" },
];

// ─── AGENT TOOLS ──────────────────────────────────────────────

const agentToolsList: AgentTool[] = [
  { agentId: "chief-of-staff", toolId: "tool-gmail", allowedActions: ["read"], approvalRequiredActions: ["send"], configuration: {}, enabled: true },
  { agentId: "chief-of-staff", toolId: "tool-calendar", allowedActions: ["read", "create"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "chief-of-staff", toolId: "tool-obsidian", allowedActions: ["read", "write"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "developer", toolId: "tool-filesystem", allowedActions: ["read", "write"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "developer", toolId: "tool-github", allowedActions: ["read", "create_branch", "commit"], approvalRequiredActions: ["push", "create_pr", "merge"], configuration: {}, enabled: true },
  { agentId: "developer", toolId: "tool-shell", allowedActions: ["execute"], approvalRequiredActions: ["destructive"], configuration: {}, enabled: true },
  { agentId: "developer", toolId: "tool-code-search", allowedActions: ["search"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "research", toolId: "tool-obsidian", allowedActions: ["read"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "research", toolId: "tool-drive", allowedActions: ["read"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "research", toolId: "tool-web-search", allowedActions: ["search"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "research", toolId: "tool-pdf-parser", allowedActions: ["extract"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "research", toolId: "tool-weather", allowedActions: ["fetch"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "legal", toolId: "tool-pdf-parser", allowedActions: ["extract"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "legal", toolId: "tool-obsidian", allowedActions: ["read", "write"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "legal", toolId: "tool-web-search", allowedActions: ["search"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "legal-case-agent", toolId: "tool-pdf-parser", allowedActions: ["extract"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "legal-case-agent", toolId: "tool-obsidian", allowedActions: ["read", "write"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "legal-case-agent", toolId: "tool-isds", allowedActions: ["read"], approvalRequiredActions: ["send"], configuration: {}, enabled: true },
  { agentId: "legal-case-agent", toolId: "tool-web-search", allowedActions: ["search"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "document", toolId: "tool-pdf-parser", allowedActions: ["extract"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "document", toolId: "tool-markdown", allowedActions: ["read", "write"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "document", toolId: "tool-obsidian", allowedActions: ["read", "write"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "document", toolId: "tool-drive", allowedActions: ["read"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "calendar", toolId: "tool-calendar", allowedActions: ["read", "create", "update", "delete"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "secretary", toolId: "tool-gmail", allowedActions: ["read", "label", "draft"], approvalRequiredActions: ["send"], configuration: {}, enabled: true },
  { agentId: "automation", toolId: "tool-shell", allowedActions: ["execute"], approvalRequiredActions: ["destructive"], configuration: {}, enabled: true },
  { agentId: "automation", toolId: "tool-n8n", allowedActions: ["trigger", "read"], approvalRequiredActions: ["modify"], configuration: {}, enabled: false },
  { agentId: "automation", toolId: "tool-home-assistant", allowedActions: ["read", "control"], approvalRequiredActions: ["critical"], configuration: {}, enabled: false },
  { agentId: "email-comm-agent", toolId: "tool-gmail", allowedActions: ["read", "label", "draft", "filter"], approvalRequiredActions: ["send"], configuration: {}, enabled: true },
  { agentId: "email-comm-agent", toolId: "tool-calendar", allowedActions: ["read"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "knowledge", toolId: "tool-obsidian", allowedActions: ["read", "write"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "knowledge", toolId: "tool-drive", allowedActions: ["read"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "knowledge", toolId: "tool-embeddings", allowedActions: ["generate"], approvalRequiredActions: [], configuration: {}, enabled: true },
  { agentId: "knowledge", toolId: "tool-vector-store", allowedActions: ["search", "index"], approvalRequiredActions: [], configuration: {}, enabled: false },
];

export function seedControlCenter(): void {
  const data: ControlCenterSeedData = {
    agents: allAgents,
    agentVersions: allAgentVersions,
    useCases: useCases,
    useCaseVersions: useCaseVersions,
    capabilities: allCapabilities,
    agentCapabilities: agentCaps,
    tools: allTools,
    agentTools: agentToolsList,
    integrations: allIntegrations,
  };

  controlCenterStore.seed(data);
  console.log(`[control-center] Seeded: ${allAgents.length} agents, ${useCases.length} use cases, ${allCapabilities.length} capabilities`);
}
