#!/usr/bin/env node
/**
 * MiLO Control Center — Seed Script
 * Populates file-based storage with all agents, use cases, and capabilities.
 *
 * Usage: tsx scripts/seed-control-center.ts
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = resolve(__dirname, "../packages/database/data/control");

if (!existsSync(DATA_DIR)) {
  mkdirSync(DATA_DIR, { recursive: true });
}

function save(file: string, data: unknown) {
  writeFileSync(resolve(DATA_DIR, file), JSON.stringify(data, null, 2), "utf-8");
  console.log(`  ✓ ${file} (${Array.isArray(data) ? data.length : Object.keys(data as Record<string, unknown>).length} entries)`);
}

const now = new Date().toISOString();

// ─── AGENTS ───────────────────────────────────────────────────────────

const agents = [
  { id: "chief-of-staff", slug: "chief-of-staff", name: "Chief of Staff", description: "Digitální ředitel kanceláře — plánuje, prioritizuje, deleguje, kontroluje, reportuje a komunikuje s uživatelem", purpose: "Koordinovat všechny agenty, připravovat denní briefing, prioritizovat a delegovat úkoly", category: "coordinator", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "critical", risk_level: "low", active_version_id: null, deployed_version_id: null, implementation_progress: 45, runtime_status: "simulated", created_at: now, updated_at: now, archived_at: null },
  { id: "developer", slug: "developer-agent", name: "Developer Agent", description: "Senior software engineer pro vývoj, code review a architekturu", purpose: "Implementovat funkce, opravovat chyby, provádět code review", category: "engineering", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "high", risk_level: "medium", active_version_id: null, deployed_version_id: null, implementation_progress: 35, runtime_status: "simulated", created_at: now, updated_at: now, archived_at: null },
  { id: "research", slug: "research-agent", name: "Research Agent", description: "Research analytik pro information retrieval, analýzu a sumarizaci", purpose: "Vyhledávat informace, analyzovat dokumenty a připravovat rešerše", category: "knowledge", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "normal", risk_level: "low", active_version_id: null, deployed_version_id: null, implementation_progress: 40, runtime_status: "simulated", created_at: now, updated_at: now, archived_at: null },
  { id: "knowledge", slug: "knowledge-agent", name: "Knowledge Agent", description: "Správce znalostní báze — indexing, vector search, knowledge graphs", purpose: "Indexovat dokumenty a zajišťovat vyhledávání napříč zdroji", category: "knowledge", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "high", risk_level: "low", active_version_id: null, deployed_version_id: null, implementation_progress: 5, runtime_status: "offline", created_at: now, updated_at: now, archived_at: null },
  { id: "legal", slug: "legal-agent", name: "Legal Agent", description: "Právní analytik pro contract analysis, legal research a compliance", purpose: "Analyzovat právní dokumenty, smlouvy a rizika", category: "legal", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "high", risk_level: "high", active_version_id: null, deployed_version_id: null, implementation_progress: 5, runtime_status: "offline", created_at: now, updated_at: now, archived_at: null },
  { id: "document", slug: "document-agent", name: "Document Agent", description: "Zpracovatel dokumentů — parsování, extrakce, generování", purpose: "Extrahovat data z dokumentů a generovat přehledné výstupy", category: "knowledge", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "normal", risk_level: "low", active_version_id: null, deployed_version_id: null, implementation_progress: 5, runtime_status: "offline", created_at: now, updated_at: now, archived_at: null },
  { id: "calendar", slug: "calendar-agent", name: "Calendar Agent", description: "Osobní manažer času — scheduling, meeting prep, focus time", purpose: "Aktivně řídit čas uživatele — synchronizovat kalendáře, detekovat kolize", category: "productivity", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "normal", risk_level: "low", active_version_id: null, deployed_version_id: null, implementation_progress: 50, runtime_status: "simulated", created_at: now, updated_at: now, archived_at: null },
  { id: "secretary", slug: "communication-agent", name: "Communication Agent", description: "Osobní komunikační manažer — email triage, AI shrnutí, návrhy odpovědí", purpose: "Řídit příchozí i odchozí komunikaci", category: "communication", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "normal", risk_level: "medium", active_version_id: null, deployed_version_id: null, implementation_progress: 45, runtime_status: "simulated", created_at: now, updated_at: now, archived_at: null },
  { id: "automation", slug: "automation-agent", name: "Automation Agent", description: "Automatizační inženýr — workflow automation, scripting", purpose: "Navrhovat a spouštět opakující se workflow", category: "engineering", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "low", risk_level: "low", active_version_id: null, deployed_version_id: null, implementation_progress: 5, runtime_status: "offline", created_at: now, updated_at: now, archived_at: null },
  { id: "legal-case-agent", slug: "legal-case-agent", name: "Právní a důkazní agent", description: "Analyzuje právní dokumenty, vytěžuje entity, lhůty, vytváří časové osy a důkazní balíčky", purpose: "Komplexní zpracování právních kauz", category: "legal", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "high", risk_level: "high", active_version_id: null, deployed_version_id: null, implementation_progress: 3, runtime_status: "offline", created_at: now, updated_at: now, archived_at: null },
  { id: "email-comm-agent", slug: "email-comm-agent", name: "E-mailový a komunikační agent", description: "Třídění Gmailu, vyhodnocení priority, návrhy odpovědí, follow-up", purpose: "Kompletní správa emailové komunikace", category: "communication", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "normal", risk_level: "medium", active_version_id: null, deployed_version_id: null, implementation_progress: 5, runtime_status: "offline", created_at: now, updated_at: now, archived_at: null },
  { id: "tjk-agent", slug: "tjk-agent", name: "TJK Agent", description: "Správa TJ Krupka — členové, příspěvky, výbor, oddíly, tréninky, soutěže", purpose: "Kompletní správa tělovýchovné jednoty", category: "organization", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "high", risk_level: "medium", active_version_id: null, deployed_version_id: null, implementation_progress: 3, runtime_status: "offline", created_at: now, updated_at: now, archived_at: null },
  { id: "komarka-agent", slug: "komarka-agent", name: "Komárka Agent", description: "Projektová dokumentace, majetková mapa, harmonogram, dotace", purpose: "Správa projektu Komárka", category: "project", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "high", risk_level: "medium", active_version_id: null, deployed_version_id: null, implementation_progress: 3, runtime_status: "offline", created_at: now, updated_at: now, archived_at: null },
  { id: "tmobile-agent", slug: "tmobile-agent", name: "T-Mobile a infrastruktura Agent", description: "Smluvní kontrola, platební kontrola, kalkulace nákladů, incident management", purpose: "Správa telekomunikační infrastruktury", category: "infrastructure", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "high", risk_level: "medium", active_version_id: null, deployed_version_id: null, implementation_progress: 3, runtime_status: "offline", created_at: now, updated_at: now, archived_at: null },
  { id: "krupka-agent", slug: "krupka-agent", name: "Město Krupka Agent", description: "Monitoring rady a zastupitelstva, kontrola usnesení, žádosti podle 106/1999 Sb.", purpose: "Monitoring a analýza městské samosprávy", category: "legal", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "normal", risk_level: "low", active_version_id: null, deployed_version_id: null, implementation_progress: 3, runtime_status: "offline", created_at: now, updated_at: now, archived_at: null },
  { id: "finance-agent", slug: "finance-agent", name: "Finanční Agent", description: "Bankovní výpisy, faktury, párování plateb, cash flow, kontrola výdajů", purpose: "Kompletní správa osobních a projektových financí", category: "finance", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "high", risk_level: "high", active_version_id: null, deployed_version_id: null, implementation_progress: 3, runtime_status: "offline", created_at: now, updated_at: now, archived_at: null },
  { id: "infra-agent", slug: "infrastructure-agent", name: "Infrastrukturní Agent", description: "Monitoring VPS, Docker, databáze, zálohování, bezpečnost", purpose: "Správa serverové infrastruktury", category: "infrastructure", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "high", risk_level: "high", active_version_id: null, deployed_version_id: null, implementation_progress: 5, runtime_status: "offline", created_at: now, updated_at: now, archived_at: null },
  { id: "webdo24-agent", slug: "webdo24-agent", name: "Webdo24 Agent", description: "Správa zákazníků, monitoring webů, expirace domén, fakturace", purpose: "Správa webhostingové firmy Webdo24", category: "business", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "normal", risk_level: "medium", active_version_id: null, deployed_version_id: null, implementation_progress: 3, runtime_status: "offline", created_at: now, updated_at: now, archived_at: null },
  { id: "personal-assistant", slug: "personal-assistant", name: "Osobní Asistent", description: "Hlasové úkoly, kalendář, připomenutí, příprava na schůzky", purpose: "Osobní asistence pro každodenní život", category: "productivity", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "normal", risk_level: "low", active_version_id: null, deployed_version_id: null, implementation_progress: 5, runtime_status: "offline", created_at: now, updated_at: now, archived_at: null },
  { id: "research-agent-intel", slug: "research-intel-agent", name: "Výzkumný a zpravodajský Agent", description: "Právní, dotační a technologický monitoring, konkurenční výzkum", purpose: "Monitoring příležitostí a hrozeb", category: "knowledge", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "normal", risk_level: "low", active_version_id: null, deployed_version_id: null, implementation_progress: 3, runtime_status: "offline", created_at: now, updated_at: now, archived_at: null },
  { id: "notifier", slug: "notifier-agent", name: "Notifier Agent", description: "Synchronizace připomínek, doručování notifikací, detekce checkpointů", purpose: "Zajistit, aby uživatel nezmeškal žádný termín", category: "productivity", owner: "owner", status: "specified", lifecycle_status: "specified", priority: "high", risk_level: "low", active_version_id: null, deployed_version_id: null, implementation_progress: 40, runtime_status: "simulated", created_at: now, updated_at: now, archived_at: null },
];

// ─── VERSIONS ──────────────────────────────────────────────────────────

const versions = agents.map((a) => ({
  id: `ver-${a.id}`,
  agent_id: a.id,
  version_number: 1,
  version_label: "v1.0-initial",
  specification: { name: a.name, purpose: a.purpose, description: a.description, category: a.category, priority: a.priority, risk_level: a.risk_level },
  change_summary: "Počáteční definice agenta",
  change_reason: "Inicializace specifikace",
  created_by: "system",
  created_at: now,
  parent_version_id: null,
  status: "draft",
  approved_at: null,
  deployed_at: null,
}));

// ─── USE CASES ────────────────────────────────────────────────────────

const useCases = [
  // Chief of Staff
  { id: "uc-cos-briefing", agent_id: "chief-of-staff", slug: "daily-briefing", name: "Denní briefing", description: "Každé ráno připravit briefing o stavu systému, prioritách a úkolech", purpose: "Poskytnout vlastníkovi přehled dne", trigger: "Spuštění každé ráno v 7:00", category: "core", priority: "critical", risk_level: "low", status: "ready_for_planning", implementation_status: "partial", progress: 30, created_at: now, updated_at: now },
  { id: "uc-cos-prioritize", agent_id: "chief-of-staff", slug: "prioritization", name: "Prioritizace úkolů", description: "Automatická prioritizace příchozích úkolů podle důležitosti a termínů", purpose: "Udržovat pořádek v backlogu", trigger: "Nový úkol nebo změna priority", category: "core", priority: "critical", risk_level: "low", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-cos-delegate", agent_id: "chief-of-staff", slug: "delegation", name: "Delegace práce", description: "Rozdělení práce mezi agenty podle jejich schopností a vytížení", purpose: "Efektivní využití všech agentů", trigger: "Nový úkol k delegování", category: "core", priority: "high", risk_level: "low", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-cos-report", agent_id: "chief-of-staff", slug: "project-overview", name: "Přehled projektů", description: "Generování přehledu všech projektů a jejich stavu", purpose: "Mít aktuální přehled o všech projektech", trigger: "Pravidelně nebo na vyžádání", category: "core", priority: "high", risk_level: "low", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },

  // Developer
  { id: "uc-dev-diagnose", agent_id: "developer", slug: "bug-diagnosis", name: "Diagnostika chyby", description: "Analýza nahlášené chyby, reprodukce, identifikace příčiny", purpose: "Rychle najít a opravit chyby", trigger: "Hlášení chyby nebo selhání testu", category: "core", priority: "critical", risk_level: "medium", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-dev-implement", agent_id: "developer", slug: "feature-implementation", name: "Implementace funkce", description: "Implementace nové funkce podle specifikace", purpose: "Dodávat nové schopnosti do systému", trigger: "Vývojový úkol", category: "core", priority: "high", risk_level: "medium", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-dev-test", agent_id: "developer", slug: "testing", name: "Testování", description: "Vytváření a spouštění testů, kontrola coverage", purpose: "Udržovat kvalitu kódu", trigger: "Po implementaci", category: "core", priority: "high", risk_level: "low", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-dev-review", agent_id: "developer", slug: "code-review", name: "Code Review", description: "Recenze kódu, kontrola architektury, bezpečnosti a kvality", purpose: "Zajistit vysokou kvalitu kódu", trigger: "Pull request nebo dokončení úkolu", category: "core", priority: "high", risk_level: "low", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },

  // Research
  { id: "uc-research-search", agent_id: "research", slug: "information-retrieval", name: "Vyhledávání informací", description: "Vyhledávání relevantních informací napříč zdroji", purpose: "Poskytovat podložené odpovědi", trigger: "Výzkumný dotaz", category: "core", priority: "high", risk_level: "low", status: "ready_for_planning", implementation_status: "partial", progress: 20, created_at: now, updated_at: now },
  { id: "uc-research-analyze", agent_id: "research", slug: "document-analysis", name: "Analýza dokumentů", description: "Hloubková analýza dokumentů a extrakce klíčových informací", purpose: "Připravit podklady pro rozhodování", trigger: "Nový dokument", category: "core", priority: "high", risk_level: "medium", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },

  // Legal Case Agent
  { id: "uc-legal-process", agent_id: "legal-case-agent", slug: "process-legal-document", name: "Zpracování právního dokumentu", description: "OCR, vytěžení lhůt, osob, organizací, částek a právních ustanovení — každý právní dokument musí kromě lhůt extrahovat také osoby, organizace, částky a právní ustanovení", purpose: "Kompletní extrakce dat z právního dokumentu", trigger: "Nahrání právního dokumentu", category: "core", priority: "critical", risk_level: "high", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-legal-ocr", agent_id: "legal-case-agent", slug: "ocr", name: "OCR", description: "Optické rozpoznávání znaků z naskenovaných dokumentů", purpose: "Digitalizovat papírové dokumenty", trigger: "Nahrání naskenovaného dokumentu", category: "core", priority: "critical", risk_level: "medium", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-legal-deadlines", agent_id: "legal-case-agent", slug: "deadline-extraction", name: "Vytěžení lhůt", description: "Extrakce všech lhůt a termínů z dokumentů", purpose: "Nepřekročit žádnou lhůtu", trigger: "Zpracování dokumentu", category: "core", priority: "critical", risk_level: "high", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-legal-entities", agent_id: "legal-case-agent", slug: "entity-extraction", name: "Vytěžení osob, organizací, částek a ustanovení", description: "Extrakce osob, organizací, finančních částek a právních ustanovení", purpose: "Strukturovaná data pro analýzu", trigger: "Zpracování dokumentu", category: "core", priority: "critical", risk_level: "high", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-legal-timeline", agent_id: "legal-case-agent", slug: "timeline-generation", name: "Vytvoření časové osy", description: "Vytvoření chronologické časové osy kauzy", purpose: "Přehledná vizualizace průběhu kauzy", trigger: "Zpracování dokumentů", category: "core", priority: "high", risk_level: "medium", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-legal-submission", agent_id: "legal-case-agent", slug: "prepare-submission", name: "Příprava podání", description: "Příprava právního podání — vyžaduje schválení před odesláním", purpose: "Generování podání s bezpečnostní kontrolou", trigger: "Schválený koncept podání", category: "core", priority: "critical", risk_level: "critical", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-legal-evidence", agent_id: "legal-case-agent", slug: "evidence-package", name: "Důkazní balíček", description: "Sestavení důkazního balíčku s propojením na entity a časovou osu", purpose: "Systematická evidence pro právní jednání", trigger: "Požadavek na důkazní balíček", category: "core", priority: "critical", risk_level: "high", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-legal-case-monitoring", agent_id: "legal-case-agent", slug: "case-monitoring", name: "Sledování kauzy", description: "Průběžné sledování stavu kauzy, nových dokumentů a termínů", purpose: "Mít aktuální přehled o každé kauze", trigger: "Pravidelně nebo při změně", category: "core", priority: "high", risk_level: "medium", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },

  // Email/Communication
  { id: "uc-email-triage", agent_id: "email-comm-agent", slug: "email-triage", name: "Třídění Gmailu", description: "Automatické třídění emailů, vytváření štítků a filtrů", purpose: "Snížit chaos v inboxu", trigger: "Nový email", category: "core", priority: "high", risk_level: "medium", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-email-priority", agent_id: "email-comm-agent", slug: "priority-assessment", name: "Vyhodnocení priority", description: "Automatické vyhodnocení priority příchozích emailů", purpose: "Nejdříve řešit důležité zprávy", trigger: "Příchozí email", category: "core", priority: "high", risk_level: "low", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-email-reply", agent_id: "email-comm-agent", slug: "draft-reply", name: "Návrh odpovědi", description: "AI generování návrhu odpovědi s možností úpravy a schválení", purpose: "Ušetřit čas při odpovídání", trigger: "Příchozí email vyžadující odpověď", category: "core", priority: "high", risk_level: "medium", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-email-followup", agent_id: "email-comm-agent", slug: "follow-up", name: "Follow-up", description: "Automatické sledování zaslaných emailů a připomenutí follow-up", purpose: "Nezapomenout na čekající odpovědi", trigger: "Email bez odpovědi po X dnech", category: "core", priority: "normal", risk_level: "low", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },

  // TJK
  { id: "uc-tjk-members", agent_id: "tjk-agent", slug: "member-management", name: "Správa členů", description: "Evidence členů, platnost registrací, oddíly", purpose: "Přehledná správa členské základny", trigger: "Změna v členské evidenci", category: "core", priority: "high", risk_level: "medium", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-tjk-fees", agent_id: "tjk-agent", slug: "membership-fees", name: "Členské příspěvky", description: "Evidence a kontrola plateb členských příspěvků", purpose: "Udržovat přehled o financích klubu", trigger: "Měsíčně nebo při platbě", category: "core", priority: "high", risk_level: "medium", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-tjk-board", agent_id: "tjk-agent", slug: "board-preparation", name: "Příprava výboru", description: "Příprava podkladů pro jednání výboru, zápis, usnesení", purpose: "Efektivní jednání výboru", trigger: "Plánované jednání výboru", category: "core", priority: "high", risk_level: "low", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },

  // Finance
  { id: "uc-fin-bank", agent_id: "finance-agent", slug: "bank-statements", name: "Bankovní výpisy", description: "Automatické zpracování bankovních výpisů, kategorizace transakcí", purpose: "Automatizace účetnictví", trigger: "Nový bankovní výpis", category: "core", priority: "critical", risk_level: "high", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-fin-invoices", agent_id: "finance-agent", slug: "invoices", name: "Faktury", description: "Evidence a správa vydaných a přijatých faktur", purpose: "Mít přehled o závazcích a pohledávkách", trigger: "Nová faktura", category: "core", priority: "high", risk_level: "medium", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-fin-match", agent_id: "finance-agent", slug: "payment-matching", name: "Párování plateb", description: "Automatické párování příchozích plateb s fakturami", purpose: "Udržovat přehled o pohledávkách", trigger: "Nová platba", category: "core", priority: "high", risk_level: "medium", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-fin-cashflow", agent_id: "finance-agent", slug: "cash-flow", name: "Cash Flow", description: "Sledování a predikce cash flow", purpose: "Vědět o finančních problémech včas", trigger: "Pravidelně týdně", category: "core", priority: "critical", risk_level: "high", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },

  // Infrastructure
  { id: "uc-infra-monitor", agent_id: "infra-agent", slug: "vps-monitoring", name: "Monitoring VPS", description: "Kontinuální monitoring serverů, CPU, RAM, disk", purpose: "Zachytit problém dříve než uživatel", trigger: "Pravidelná kontrola / alert", category: "core", priority: "critical", risk_level: "high", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-infra-backup", agent_id: "infra-agent", slug: "backup", name: "Zálohování", description: "Automatické zálohování databází, souborů, konfigurací", purpose: "Ochrana proti ztrátě dat", trigger: "Plánované denně/týdně", category: "core", priority: "critical", risk_level: "high", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-infra-docker", agent_id: "infra-agent", slug: "docker-management", name: "Docker", description: "Správa Docker kontejnerů — start, stop, health check", purpose: "Spolehlivý běh služeb", trigger: "Pravidelná kontrola", category: "core", priority: "high", risk_level: "medium", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-infra-security", agent_id: "infra-agent", slug: "security", name: "Bezpečnost", description: "Bezpečnostní monitoring, aktualizace, certifikáty", purpose: "Udržovat bezpečnost infrastruktury", trigger: "Pravidelná kontrola", category: "core", priority: "critical", risk_level: "high", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },

  // Krupka
  { id: "uc-krupka-monitor", agent_id: "krupka-agent", slug: "council-monitoring", name: "Monitoring rady a zastupitelstva", description: "Sledování programu, usnesení a hlasování", purpose: "Transparentnost místní samosprávy", trigger: "Zveřejnění programu jednání", category: "core", priority: "high", risk_level: "low", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-krupka-106", agent_id: "krupka-agent", slug: "info-request", name: "Žádosti podle 106/1999 Sb.", description: "Příprava a sledování žádostí o informace", purpose: "Efektivní využití zákona o svobodném přístupu k informacím", trigger: "Potřeba získat informace", category: "core", priority: "high", risk_level: "low", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-krupka-voting", agent_id: "krupka-agent", slug: "voting-analysis", name: "Analýza hlasování", description: "Analýza hlasování zastupitelů, detekce střetu zájmů", purpose: "Odhalit potenciální střety zájmů", trigger: "Zveřejnění výsledků hlasování", category: "core", priority: "normal", risk_level: "low", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },

  // Komárka
  { id: "uc-komarka-docs", agent_id: "komarka-agent", slug: "project-documentation", name: "Projektová dokumentace", description: "Správa a verzování projektové dokumentace", purpose: "Udržovat aktuální dokumentaci projektu", trigger: "Nová verze dokumentace", category: "core", priority: "high", risk_level: "medium", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-komarka-grants", agent_id: "komarka-agent", slug: "grant-opportunities", name: "Dotační příležitosti", description: "Monitoring a vyhodnocování dotačních příležitostí", purpose: "Získat financování pro projekt", trigger: "Vyhlášení nové výzvy", category: "core", priority: "high", risk_level: "medium", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },

  // T-Mobile
  { id: "uc-tmobile-contracts", agent_id: "tmobile-agent", slug: "contract-review", name: "Smluvní kontrola", description: "Kontrola smluv a podmínek poskytovatele", purpose: "Optimalizovat náklady na služby", trigger: "Pravidelně nebo při změně", category: "core", priority: "high", risk_level: "medium", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },

  // Webdo24
  { id: "uc-webdo-customers", agent_id: "webdo24-agent", slug: "customer-management", name: "Správa zákazníků", description: "Evidence zákazníků, jejich služeb a historie", purpose: "Mít přehled o všech zákaznících", trigger: "Nový zákazník nebo změna", category: "core", priority: "high", risk_level: "medium", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-webdo-domains", agent_id: "webdo24-agent", slug: "domain-expiration", name: "Expirace domén", description: "Monitoring expirace domén a SSL certifikátů", purpose: "Nezmeškat obnovení domény", trigger: "Pravidelná kontrola", category: "core", priority: "critical", risk_level: "high", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },

  // Personal Assistant
  { id: "uc-pa-voice", agent_id: "personal-assistant", slug: "voice-tasks", name: "Hlasové úkoly", description: "Příjem a zpracování hlasových úkolů", purpose: "Rychlé zadávání úkolů", trigger: "Hlasový příkaz", category: "core", priority: "normal", risk_level: "low", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-pa-meeting", agent_id: "personal-assistant", slug: "meeting-prep", name: "Příprava na schůzku", description: "Automatická příprava podkladů pro schůzku", purpose: "Být připraven na každou schůzku", trigger: "Nadcházející schůzka v kalendáři", category: "core", priority: "normal", risk_level: "low", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },

  // Research Intel
  { id: "uc-intel-legal", agent_id: "research-agent-intel", slug: "legal-monitoring", name: "Právní monitoring", description: "Monitoring legislativních změn a nových předpisů", purpose: "Být informován o právních změnách", trigger: "Pravidelně týdně", category: "core", priority: "normal", risk_level: "low", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
  { id: "uc-intel-tech", agent_id: "research-agent-intel", slug: "technology-monitoring", name: "Technologický monitoring", description: "Sledování nových technologií a nástrojů", purpose: "Držet krok s technologickým vývojem", trigger: "Pravidelně měsíčně", category: "core", priority: "normal", risk_level: "low", status: "draft", implementation_status: "not_started", progress: 0, created_at: now, updated_at: now },
];

// ─── CAPABILITIES ──────────────────────────────────────────────────────

const capabilities = [
  { id: "cap-pdf-parsing", capability_code: "pdf_parsing", name: "PDF Parsing", description: "Extrakce textu, metadat a struktury z PDF dokumentů", status: "planned", maturity_level: "concept", owner: "engineering", created_at: now, updated_at: now },
  { id: "cap-ocr", capability_code: "ocr", name: "OCR", description: "Optické rozpoznávání znaků z obrázků a naskenovaných dokumentů", status: "planned", maturity_level: "concept", owner: "engineering", created_at: now, updated_at: now },
  { id: "cap-metadata-extraction", capability_code: "metadata_extraction", name: "Metadata Extraction", description: "Extrakce strukturovaných metadat z dokumentů (lhůty, osoby, organizace, částky)", status: "planned", maturity_level: "concept", owner: "engineering", created_at: now, updated_at: now },
  { id: "cap-deadline-extraction", capability_code: "deadline_extraction", name: "Deadline Extraction", description: "Vytěžení lhůt a termínů z dokumentů", status: "planned", maturity_level: "concept", owner: "engineering", created_at: now, updated_at: now },
  { id: "cap-legal-entity-extraction", capability_code: "legal_entity_extraction", name: "Legal Entity Extraction", description: "Vytěžení osob, organizací, částek a právních ustanovení", status: "planned", maturity_level: "concept", owner: "engineering", created_at: now, updated_at: now },
  { id: "cap-timeline-generation", capability_code: "timeline_generation", name: "Timeline Generation", description: "Vytvoření časové osy z událostí a lhůt", status: "planned", maturity_level: "concept", owner: "engineering", created_at: now, updated_at: now },
  { id: "cap-evidence-linking", capability_code: "evidence_linking", name: "Evidence Linking", description: "Propojování důkazních dokumentů s entitami a tvrzeními", status: "planned", maturity_level: "concept", owner: "engineering", created_at: now, updated_at: now },
  { id: "cap-email-triage", capability_code: "email_triage", name: "Email Triage", description: "Třídění Gmailu, vytváření štítků a nastavování filtrů", status: "planned", maturity_level: "concept", owner: "engineering", created_at: now, updated_at: now },
  { id: "cap-ai-summary", capability_code: "ai_summary", name: "AI Summary", description: "AI shrnutí zpráv, dokumentů a konverzací", status: "planned", maturity_level: "concept", owner: "engineering", created_at: now, updated_at: now },
  { id: "cap-code-search", capability_code: "code_search", name: "Code Search", description: "Vyhledávání v kódu, diagnostika chyb", status: "planned", maturity_level: "concept", owner: "engineering", created_at: now, updated_at: now },
  { id: "cap-git-operations", capability_code: "git_operations", name: "Git Operations", description: "Práce s gitem — branch, commit, push, pull request", status: "planned", maturity_level: "concept", owner: "engineering", created_at: now, updated_at: now },
  { id: "cap-payment-matching", capability_code: "payment_matching", name: "Payment Matching", description: "Automatické párování plateb s fakturami", status: "planned", maturity_level: "concept", owner: "engineering", created_at: now, updated_at: now },
];

// ─── COMPONENTS ────────────────────────────────────────────────────────

const components = [
  // Existing implemented components
  { id: "comp-aos-core", agent_id: "chief-of-staff", use_case_id: null, capability_id: null, component_type: "backend", name: "AOS AgentManager", repository: "MiLO_Core", file_path: "packages/agents/src/agent-manager.ts", module_name: "agent-manager", implementation_status: "implemented", test_status: "tested", deployed_status: "deployed", created_at: now },
  { id: "comp-aos-events", agent_id: "chief-of-staff", use_case_id: null, capability_id: null, component_type: "backend", name: "AgentEventBus", repository: "MiLO_Core", file_path: "packages/agents/src/event-bus.ts", module_name: "event-bus", implementation_status: "implemented", test_status: "tested", deployed_status: "deployed", created_at: now },
  { id: "comp-cos-agent", agent_id: "chief-of-staff", use_case_id: "uc-cos-briefing", capability_id: null, component_type: "workflow", name: "ChiefOfStaffAgent", repository: "MiLO_Core", file_path: "packages/agents/src/agents/chief-of-staff.ts", module_name: "chief-of-staff", implementation_status: "implemented", test_status: "tested", deployed_status: "deployed", created_at: now },
  { id: "comp-cal-service", agent_id: "calendar", use_case_id: null, capability_id: null, component_type: "backend", name: "CalendarService", repository: "MiLO_Core", file_path: "packages/agents/src/services/calendar/index.ts", module_name: "calendar-service", implementation_status: "implemented", test_status: "tested", deployed_status: "deployed", created_at: now },
  { id: "comp-comm-service", agent_id: "secretary", use_case_id: null, capability_id: null, component_type: "backend", name: "CommunicationService", repository: "MiLO_Core", file_path: "packages/agents/src/services/communication/index.ts", module_name: "communication-service", implementation_status: "implemented", test_status: "tested", deployed_status: "deployed", created_at: now },
  // Not yet implemented
  { id: "comp-legal-doc-parser", agent_id: "legal-case-agent", use_case_id: "uc-legal-process", capability_id: "cap-pdf-parsing", component_type: "backend", name: "DocumentParser", repository: "MiLO_Core", file_path: null, module_name: null, implementation_status: "not_started", test_status: "none", deployed_status: "none", created_at: now },
  { id: "comp-legal-entity-extractor", agent_id: "legal-case-agent", use_case_id: "uc-legal-entities", capability_id: "cap-legal-entity-extraction", component_type: "backend", name: "EntityExtractor", repository: "MiLO_Core", file_path: null, module_name: null, implementation_status: "not_started", test_status: "none", deployed_status: "none", created_at: now },
  { id: "comp-legal-timeline", agent_id: "legal-case-agent", use_case_id: "uc-legal-timeline", capability_id: "cap-timeline-generation", component_type: "backend", name: "TimelineService", repository: "MiLO_Core", file_path: null, module_name: null, implementation_status: "not_started", test_status: "none", deployed_status: "none", created_at: now },
  { id: "comp-fin-bank-parser", agent_id: "finance-agent", use_case_id: "uc-fin-bank", capability_id: null, component_type: "backend", name: "BankStatementParser", repository: "MiLO_Core", file_path: null, module_name: null, implementation_status: "not_started", test_status: "none", deployed_status: "none", created_at: now },
  { id: "comp-fin-matcher", agent_id: "finance-agent", use_case_id: "uc-fin-match", capability_id: "cap-payment-matching", component_type: "backend", name: "PaymentMatcher", repository: "MiLO_Core", file_path: null, module_name: null, implementation_status: "not_started", test_status: "none", deployed_status: "none", created_at: now },
  { id: "comp-infra-monitor", agent_id: "infra-agent", use_case_id: "uc-infra-monitor", capability_id: null, component_type: "backend", name: "VpsMonitor", repository: "MiLO_Core", file_path: null, module_name: null, implementation_status: "not_started", test_status: "none", deployed_status: "none", created_at: now },
];

// ─── WRITE ALL FILES ───────────────────────────────────────────────────

console.log("\n🌱 MiLO Control Center — Seed\n");
save("agents.json", agents);
save("agent-versions.json", versions);
save("use-cases.json", useCases);
save("capabilities.json", capabilities);
save("components.json", components);
save("tasks.json", []);
save("missions.json", []);
save("audits.json", []);
save("deployments.json", []);

console.log(`\n✅ Seed complete — ${agents.length} agents, ${useCases.length} use cases, ${capabilities.length} capabilities, ${components.length} components`);
